server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:    gateway:
      # service registry에 있는 서비스명으로 라우팅처리
      # /service-1/** -> service-1물리주소/**
      discovery:        locator:          enabled: true          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"