INSERT INTO product(id, product_name, category, price) VALUES(1,'Chais',lower('Beverages'),round(18));
INSERT INTO product(id, product_name, category, price) VALUES(2,'Chang',lower('Beverages'),round(19));
INSERT INTO product(id, product_name, category, price) VALUES(3,'Aniseed Syrup',lower('Condiments'),round(10));
INSERT INTO product(id, product_name, category, price) VALUES(4,'Chef Anton`s Cajun Seasoning',lower('Condiments'),round(22));
INSERT INTO product(id, product_name, category, price) VALUES(5,'Chef Anton`s Gumbo Mix',lower('Condiments'),round(21.35));
INSERT INTO product(id, product_name, category, price) VALUES(6,'Grandma`s Boysenberry Spread',lower('Condiments'),round(25));
INSERT INTO product(id, product_name, category, price) VALUES(7,'Uncle Bob`s Organic Dried Pears',lower('Produce'),round(30));
INSERT INTO product(id, product_name, category, price) VALUES(8,'Northwoods Cranberry Sauce',lower('Condiments'),round(40));
INSERT INTO product(id, product_name, category, price) VALUES(9,'Mishi Kobe Niku',lower('MeatPoultry'),round(97));
INSERT INTO product(id, product_name, category, price) VALUES(10,'Ikura',lower('Seafood'),round(31));
INSERT INTO product(id, product_name, category, price) VALUES(11,'Queso Cabrales',lower('DairyProducts'),round(21));
INSERT INTO product(id, product_name, category, price) VALUES(12,'Queso Manchego La Pastora',lower('DairyProducts'),round(38));
INSERT INTO product(id, product_name, category, price) VALUES(13,'Konbu',lower('Seafood'),round(6));
INSERT INTO product(id, product_name, category, price) VALUES(14,'Tofu',lower('Produce'),round(23.25));
INSERT INTO product(id, product_name, category, price) VALUES(15,'Genen Shouyu',lower('Condiments'),round(15.5));
INSERT INTO product(id, product_name, category, price) VALUES(16,'Pavlova',lower('Confections'),round(17.45));
INSERT INTO product(id, product_name, category, price) VALUES(17,'Alice Mutton',lower('MeatPoultry'),round(39));
INSERT INTO product(id, product_name, category, price) VALUES(18,'Carnarvon Tigers',lower('Seafood'),round(62.5));
INSERT INTO product(id, product_name, category, price) VALUES(19,'Teatime Chocolate Biscuits',lower('Confections'),round(9.2));
INSERT INTO product(id, product_name, category, price) VALUES(20,'Sir Rodney`s Marmalade',lower('Confections'),round(81));
INSERT INTO product(id, product_name, category, price) VALUES(21,'Sir Rodney`s Scones',lower('Confections'),round(10));
INSERT INTO product(id, product_name, category, price) VALUES(22,'Gustaf`s Knäckebröd',lower('GrainsCereals'),round(21));
INSERT INTO product(id, product_name, category, price) VALUES(23,'Tunnbröd',lower('GrainsCereals'),round(9));
INSERT INTO product(id, product_name, category, price) VALUES(24,'Guaraná Fantástica',lower('Beverages'),round(4.5));
INSERT INTO product(id, product_name, category, price) VALUES(25,'NuNuCa Nuß-Nougat-Creme',lower('Confections'),round(14));
INSERT INTO product(id, product_name, category, price) VALUES(26,'Gumbär Gummibärchen',lower('Confections'),round(31.23));
INSERT INTO product(id, product_name, category, price) VALUES(27,'Schoggi Schokolade',lower('Confections'),round(43.9));
INSERT INTO product(id, product_name, category, price) VALUES(28,'Rössle Sauerkraut',lower('Produce'),round(45.6));
INSERT INTO product(id, product_name, category, price) VALUES(29,'Thüringer Rostbratwurst',lower('MeatPoultry'),round(123.79));
INSERT INTO product(id, product_name, category, price) VALUES(30,'Nord-Ost Matjeshering',lower('Seafood'),round(25.89));
INSERT INTO product(id, product_name, category, price) VALUES(31,'Gorgonzola Telino',lower('DairyProducts'),round(12.5));
INSERT INTO product(id, product_name, category, price) VALUES(32,'Mascarpone Fabioli',lower('DairyProducts'),round(32));
INSERT INTO product(id, product_name, category, price) VALUES(33,'Geitost',lower('DairyProducts'),round(2.5));
INSERT INTO product(id, product_name, category, price) VALUES(34,'Sasquatch Ale',lower('Beverages'),round(14));
INSERT INTO product(id, product_name, category, price) VALUES(35,'Steeleye Stout',lower('Beverages'),round(18));
INSERT INTO product(id, product_name, category, price) VALUES(36,'Inlagd Sill',lower('Seafood'),round(19));
INSERT INTO product(id, product_name, category, price) VALUES(37,'Gravad lax',lower('Seafood'),round(26));
INSERT INTO product(id, product_name, category, price) VALUES(38,'Côte de Blaye',lower('Beverages'),round(263.5));
INSERT INTO product(id, product_name, category, price) VALUES(39,'Chartreuse verte',lower('Beverages'),round(18));
INSERT INTO product(id, product_name, category, price) VALUES(40,'Boston Crab Meat',lower('Seafood'),round(18.4));
INSERT INTO product(id, product_name, category, price) VALUES(41,'Jack`s New England Clam Chowder',lower('Seafood'),round(9.65));
INSERT INTO product(id, product_name, category, price) VALUES(42,'Singaporean Hokkien Fried Mee',lower('GrainsCereals'),round(14));
INSERT INTO product(id, product_name, category, price) VALUES(43,'Ipoh Coffee',lower('Beverages'),round(46));
INSERT INTO product(id, product_name, category, price) VALUES(44,'Gula Malacca',lower('Condiments'),round(19.45));
INSERT INTO product(id, product_name, category, price) VALUES(45,'Røgede sild',lower('Seafood'),round(9.5));
INSERT INTO product(id, product_name, category, price) VALUES(46,'Spegesild',lower('Seafood'),round(12));
INSERT INTO product(id, product_name, category, price) VALUES(47,'Zaanse koeken',lower('Confections'),round(9.5));
INSERT INTO product(id, product_name, category, price) VALUES(48,'Chocolade',lower('Confections'),round(12.75));
INSERT INTO product(id, product_name, category, price) VALUES(49,'Maxilaku',lower('Confections'),round(20));
INSERT INTO product(id, product_name, category, price) VALUES(50,'Valkoinen suklaa',lower('Confections'),round(16.25));
INSERT INTO product(id, product_name, category, price) VALUES(51,'Manjimup Dried Apples',lower('Produce'),round(53));
INSERT INTO product(id, product_name, category, price) VALUES(52,'Filo Mix',lower('GrainsCereals'),round(7));
INSERT INTO product(id, product_name, category, price) VALUES(53,'Perth Pasties',lower('MeatPoultry'),round(32.8));
INSERT INTO product(id, product_name, category, price) VALUES(54,'Tourtière',lower('MeatPoultry'),round(7.45));
INSERT INTO product(id, product_name, category, price) VALUES(55,'Pâté chinois',lower('MeatPoultry'),round(24));
INSERT INTO product(id, product_name, category, price) VALUES(56,'Gnocchi di nonna Alice',lower('GrainsCereals'),round(38));
INSERT INTO product(id, product_name, category, price) VALUES(57,'Ravioli Angelo',lower('GrainsCereals'),round(19.5));
INSERT INTO product(id, product_name, category, price) VALUES(58,'Escargots de Bourgogne',lower('Seafood'),round(13.25));
INSERT INTO product(id, product_name, category, price) VALUES(59,'Raclette Courdavault',lower('DairyProducts'),round(55));
INSERT INTO product(id, product_name, category, price) VALUES(60,'Camembert Pierrot',lower('DairyProducts'),round(34));
INSERT INTO product(id, product_name, category, price) VALUES(61,'Sirop d`érable',lower('Condiments'),round(28.5));
INSERT INTO product(id, product_name, category, price) VALUES(62,'Tarte au sucre',lower('Confections'),round(49.3));
INSERT INTO product(id, product_name, category, price) VALUES(63,'Vegie-spread',lower('Condiments'),round(43.9));
INSERT INTO product(id, product_name, category, price) VALUES(64,'Wimmers gute Semmelknödel',lower('GrainsCereals'),round(33.25));
INSERT INTO product(id, product_name, category, price) VALUES(65,'Louisiana Fiery Hot Pepper Sauce',lower('Condiments'),round(21.05));
INSERT INTO product(id, product_name, category, price) VALUES(66,'Louisiana Hot Spiced Okra',lower('Condiments'),round(17));
INSERT INTO product(id, product_name, category, price) VALUES(67,'Laughing Lumberjack Lager',lower('Beverages'),round(14));
INSERT INTO product(id, product_name, category, price) VALUES(68,'Scottish Longbreads',lower('Confections'),round(12.5));
INSERT INTO product(id, product_name, category, price) VALUES(69,'Gudbrandsdalsost',lower('DairyProducts'),round(36));
INSERT INTO product(id, product_name, category, price) VALUES(70,'Outback Lager',lower('Beverages'),round(15));
INSERT INTO product(id, product_name, category, price) VALUES(71,'Fløtemysost',lower('DairyProducts'),round(21.5));
INSERT INTO product(id, product_name, category, price) VALUES(72,'Mozzarella di Giovanni',lower('DairyProducts'),round(34.8));
INSERT INTO product(id, product_name, category, price) VALUES(73,'Röd Kaviar',lower('Seafood'),round(15));
INSERT INTO product(id, product_name, category, price) VALUES(74,'Longlife Tofu',lower('Produce'),round(10));
INSERT INTO product(id, product_name, category, price) VALUES(75,'Rhönbräu Klosterbier',lower('Beverages'),round(7.75));
INSERT INTO product(id, product_name, category, price) VALUES(76,'Lakkalikööri',lower('Beverages'),round(18));
INSERT INTO product(id, product_name, category, price) VALUES(77,'Original Frankfurter grüne Soße',lower('Condiments'),round(13));
