-- sales.sales_order definition

-- Drop table

-- DROP TABLE sales.sales_order;

CREATE TABLE sales.sales_order (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	address varchar(255) NULL,
	created_time int8 NULL,
	"date" varchar(255) NULL,
	"name" varchar(255) NULL,
	status varchar(255) NULL,
	total_amount int8 NULL,
	CONSTRAINT sales_order_pkey PRIMARY KEY (id)
);